"""initial schema

Revision ID: 6728e0cb4005
Revises: 
Create Date: 2026-02-25 05:25:42.115663
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6728e0cb4005'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('webhook_url', sa.Text(), nullable=True))
    op.add_column('operators', sa.Column('api_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'api_key')
    op.drop_column('operators', 'webhook_url')
    # ### end Alembic commands ###
